"""first commit

Revision ID: eea22cf09372
Revises: 
Create Date: 2025-01-18 20:44:59.454685

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eea22cf09372'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_name', sa.String(), nullable=False),
    sa.Column('work_duration', sa.Integer(), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('long_break_duration', sa.Integer(), nullable=True),
    sa.Column('work_intervals', sa.Integer(), nullable=True),
    sa.Column('autostart_work', sa.Boolean(), nullable=True),
    sa.Column('autostart_break', sa.Boolean(), nullable=True),
    sa.Column('enable_website_filter', sa.Boolean(), nullable=True),
    sa.Column('website_filter_type', sa.Enum('BLOCKLIST', 'ALLOWLIST', name='websitefiltertype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowlist_exception_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowlist_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocklist_exception_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocklist_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_workspace_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('task_type', sa.Enum('TODO', 'COMPLETED', name='tasktype'), nullable=True),
    sa.Column('task_position', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('target_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('current_workspace')
    op.drop_table('blocklist_urls')
    op.drop_table('blocklist_exception_urls')
    op.drop_table('allowlist_urls')
    op.drop_table('allowlist_exception_urls')
    op.drop_table('workspaces')
    op.drop_table('version')
    # ### end Alembic commands ###
